import { IBank } from './iranian-banks.types';

export const Banks: IBank[] = [
  {
    code: '010',
    name: 'Central Bank of Iran',
    persianName: 'بانک مرکزی جمهوری اسلامی ایران',
    cardCodes: ['636795'],
  },
  {
    code: '011',
    name: 'Sanat O Madan Bank',
    persianName: 'بانک صنعت و معدن',
    cardCodes: ['627961'],
  },
  {
    code: '012',
    name: 'Mellat Bank',
    persianName: 'بانک ملت',
    cardCodes: ['610433', '991975'],
  },
  {
    code: '013',
    name: 'Refah Bank',
    persianName: 'بانک رفاه کارگران',
    cardCodes: ['589463'],
  },
  {
    code: '014',
    name: 'Maskan Bank',
    persianName: 'بانک مسکن',
    cardCodes: ['628023'],
  },
  {
    code: '015',
    name: 'Sepah Bank',
    persianName: 'بانک سپه',
    cardCodes: ['589210'],
  },
  {
    code: '016',
    name: 'Keshavarzi',
    persianName: 'بانک کشاورزی',
    cardCodes: ['603770', '639217'],
  },
  {
    code: '017',
    name: 'Melli',
    persianName: 'بانک ملی ایران',
    cardCodes: ['170019', '603799'],
  },
  {
    code: '018',
    name: 'Tejarat Bank',
    persianName: 'بانک تجارت',
    cardCodes: ['585983', '627353'],
  },
  {
    code: '019',
    name: 'Saderat Bank',
    persianName: 'بانک صادرات ایران',
    cardCodes: ['603769', '903769'],
  },
  {
    code: '020',
    name: 'Tose Saderat Bank',
    persianName: 'بانک توسعه صادرات',
    cardCodes: ['207177', '627648'],
  },
  {
    code: '021',
    name: 'Post Bank',
    persianName: 'پست بانک ایران',
    cardCodes: ['627760'],
  },
  {
    code: '022',
    name: 'Tosee Taavon Bank',
    persianName: 'بانک توسعه تعاون',
    cardCodes: ['502908'],
  },
  {
    code: '051',
    name: 'Tosee Bank',
    persianName: 'موسسه اعتباری توسعه',
    cardCodes: ['628157'],
  },
  {
    code: '052',
    name: 'Ghavamin Bank',
    persianName: 'بانک قوامین',
    cardCodes: ['639599'],
  },
  {
    code: '053',
    name: 'Karafarin Bank',
    persianName: 'بانک کارآفرین',
    cardCodes: ['627488', '502910'],
  },
  {
    code: '054',
    name: 'Parsian Bank',
    persianName: 'بانک پارسیان',
    cardCodes: ['622106', '627884', '639194'],
  },
  {
    code: '055',
    name: 'Eghtesad Novin Bank',
    persianName: 'بانک اقتصاد نوین',
    cardCodes: ['627412'],
  },
  {
    code: '056',
    name: 'Saman Bank',
    persianName: 'بانک سامان',
    cardCodes: ['621986'],
  },
  {
    code: '057',
    name: 'Pasargad Bank',
    persianName: 'بانک پاسارگاد',
    cardCodes: ['502229', '639347'],
  },
  {
    code: '058',
    name: 'Sarmayeh Bank',
    persianName: 'بانک سرمایه',
    cardCodes: ['639607'],
  },
  {
    code: '059',
    name: 'Sina Bank',
    persianName: 'بانک سینا',
    cardCodes: ['639346'],
  },
  {
    code: '060',
    name: 'Mehr Iran Bank',
    persianName: 'بانک مهر ایران',
    cardCodes: ['606373'],
  },
  {
    code: '061',
    name: 'City Bank',
    persianName: 'بانک شهر',
    cardCodes: ['502806', '504706'],
  },
  {
    code: '062',
    name: 'Ayandeh Bank',
    persianName: 'بانک آینده',
    cardCodes: ['636214'],
  },
  {
    code: '063',
    name: 'Ansar Bank',
    persianName: 'بانک انصار',
    cardCodes: ['627381'],
  },
  {
    code: '064',
    name: 'Gardeshgari Bank',
    persianName: 'بانک گردشگری',
    cardCodes: ['505416', '505426'],
  },
  {
    code: '065',
    name: 'Hekmat Iranian Bank',
    persianName: 'بانک حکمت ایرانیان',
    cardCodes: ['636949'],
  },
  {
    code: '066',
    name: 'Dey Bank',
    persianName: 'بانک دی',
    cardCodes: ['502938'],
  },
  {
    code: '069',
    name: 'Iran Zamin Bank',
    persianName: 'بانک ایران زمین',
    cardCodes: ['505785'],
  },
  {
    code: '070',
    name: 'Resalat Bank',
    persianName: 'بانک قرض الحسنه رسالت',
    cardCodes: ['504172'],
  },
  {
    code: '073',
    name: 'Kosar Credit Institute',
    persianName: 'موسسه اعتباری کوثر',
    cardCodes: ['505801'],
  },
  {
    code: '075',
    name: 'Melal Credit Institute',
    persianName: 'موسسه اعتباری ملل',
    cardCodes: ['606256'],
  },
  {
    code: '078',
    name: 'Middle East Bank',
    persianName: 'بانک خاورمیانه',
    cardCodes: ['585949'],
  },
  {
    code: '080',
    name: 'Noor Credit Institution',
    persianName: 'موسسه اعتباری نور',
    cardCodes: [],
  },
  {
    code: '079',
    name: 'Mehr Eqtesad Bank',
    persianName: 'بانک مهر اقتصاد',
    cardCodes: ['639370'],
  },
  {
    code: '090',
    name: 'Mehr Iran Bank',
    persianName: 'بانک مهر ایران',
    cardCodes: [],
  },
  {
    code: '095',
    name: 'Iran and Venezuela Bank',
    persianName: 'بانک ایران و ونزوئلا',
    cardCodes: [],
  },
];
