name: Build & Deploy Mirza

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/mirza

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      MIRZA_CHANGED: ${{ steps.affected.outputs.MIRZA_CHANGED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Define Docker TAG
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]/-/g')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "Docker tag will be: ${BRANCH_NAME}-${SHORT_SHA}"

      - name: Check if Mirza app is affected
        id: affected
        run: |
          npx nx show projects --affected --base=origin/master --head=HEAD | grep -q '^mirza$' && echo "MIRZA_CHANGED=true" >> $GITHUB_OUTPUT || echo "MIRZA_CHANGED=false" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.mirza -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
          docker tag $IMAGE_NAME:${{ steps.vars.outputs.TAG }} $IMAGE_NAME:${GITHUB_REF##*/}

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          docker push $IMAGE_NAME:${GITHUB_REF##*/}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.MIRZA_CHANGED == 'true' && github.event_name == 'push'

    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to K3s
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]/-/g')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG=${BRANCH_NAME}-${SHORT_SHA}
          kubectl set image deployment/angular-app angular-app=${{ secrets.DOCKER_USERNAME }}/mirza:$TAG
          kubectl rollout status deployment/angular-app