name: Mirza Manual Deploy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.MIRZA_DOCKER_USERNAME }}/mirza

jobs:
  build-and-deploy-mirza:
    name: Deploy mirza (Production - Master)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Define Docker TAG
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=prod-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "Docker tag will be: prod-${SHORT_SHA}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MIRZA_DOCKER_USERNAME }}
          password: ${{ secrets.MIRZA_DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          MIRZA_SENTRY_DSN_PRODUCTION: ${{ secrets.MIRZA_SENTRY_DSN_PRODUCTION }}
        run: |
          node tools/generate-mirza-production-env.mjs
          docker build -f Dockerfile.mirza.production -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
          docker tag $IMAGE_NAME:${{ steps.vars.outputs.TAG }} $IMAGE_NAME:latest

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          docker push $IMAGE_NAME:latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.MIRZA_KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to K3s
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG=prod-${SHORT_SHA}
          kubectl set image deployment/angular-app angular-app=${{ secrets.MIRZA_DOCKER_USERNAME }}/mirza:$TAG
          kubectl rollout status deployment/angular-app
